name: "App: Update libphonenumber"

on:
  workflow_dispatch:
    inputs:
      jira-ticket:
        type: string
        required: true

jobs:
  build-libphonenumber:
    name: "Build libphonenumber"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: google/libphonenumber
          ref: "v8.13.42"
          fetch-depth: 0 
      - name: Get lib versions
        run: |
          BRANCH_NAME="feature/${{ github.event.inputs.jira-ticket }}"
          git checkout -b ${BRANCH_NAME}

          touch file
          git add .

          COMMIT_MESSAGE="${{ github.event.inputs.jira-ticket }}: Update libphonenumber to"
          git commit -m "${COMMIT_MESSAGE}"
