name: "App: Update libphonenumber"

on:
  workflow_dispatch:

jobs:
  build-libphonenumber:
    name: "Build libphonenumber"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: google/libphonenumber
          ref: "v8.13.42"
          fetch-depth: 0 
      - name: Get lib versions
        run: |
          MAVEN_OUTPUT=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -pl java/carrier)
          # Trim any leading or trailing whitespace and export the result
          echo "CARRIER_VERSION=$(echo $MAVEN_OUTPUT | xargs)" >> $GITHUB_ENV

          MAVEN_OUTPUT=$(mvn dependency:list -pl java/carrier | grep 'com.googlecode.libphonenumber:prefixmapper' | awk -F: '{print $4}')
          # Trim any leading or trailing whitespace and export the result
          echo "PREFIXMAPPER_VERSION=$(echo $MAVEN_OUTPUT | xargs)" >> $GITHUB_ENV
      - name: Create artifacts directory
        run: mkdir artifacts
      - name: Download artifacts
        run: |
          curl -O https://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/8.13.42/libphonenumber-8.13.42-no-metadata.jar -o artifacts
          curl -O https://repo1.maven.org/maven2/com/googlecode/libphonenumber/carrier/${{ env.CARRIER_VERSION }}/carrier-${{ env.CARRIER_VERSION }}.jar -o artifacts
          curl -O https://repo1.maven.org/maven2/com/googlecode/libphonenumber/prefixmapper/${{ env.PREFIXMAPPER_VERSION }}/prefixmapper-${{ env.PREFIXMAPPER_VERSION }}.jar -o artifacts
      - name: Copy METADATA
        run: cp -R java/libphonenumber/src/com/google/i18n/phonenumbers/data/ artifacts/metadata
      - uses: actions/upload-artifact@v4
        with:
          name: libphonenumber-artifacts
          if-no-files-found: error
          path: artifacts/*
