name: "App: Update libphonenumber"

on:
  workflow_dispatch:

jobs:
  build-libphonenumber:
    name: "Build libphonenumber"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: google/libphonenumber
          ref: "v8.13.42"
          fetch-depth: 0 
      - name: Get lib versions
        run: |
          echo "CARRIER_VERSION=$(echo (mvn help:evaluate -Dexpression=project.version -q -DforceStdout -pl java/carrier))" >> $GITHUB_ENV

          OUTPUT=$(mvn help:evaluate -Dexpression=project.dependencies | grep -A 2 'com.googlecode.libphonenumber:carrier' | awk -F: '{print $4})
          echo "PREFIXMAPPER_VERSION=${OUTPUT}" >> $GITHUB_ENV
      - name: Download carrier jar
        run: echo $CARRIER_VERSION
      - uses: actions/upload-artifact@v4
        with:
          name: libphonenumber-artifacts
          if-no-files-found: error
          path: |
            /carrier-*.jar
            /prefixmapper-*.jar
            java/libphonenumber/target/libphonenumber-*-no-metadata.jar
            java/libphonenumber/src/com/google/i18n/phonenumbers/data/*
            
