name: "App: Update libphonenumber"

on:
  workflow_dispatch:

jobs:
  build-libphonenumber:
    name: "Build libphonenumber"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: google/libphonenumber
          ref: "v8.13.42"
          fetch-depth: 0  
      - name: Get lib versions
        id: get-lib-versions
        run: echo "CARRIER_VERSION = mvn help:evaluate -Dexpression=project.version -q -DforceStdout -pl java/carrier" >> $CARRIER_VERSION
        # echo "PREFIXMAPPER_VERSION = mvn help:evaluate -Dexpression=project.dependencies | grep -A 2 'com.googlecode.libphonenumber:carrier' | awk -F: '{print $4}" >> $PREFIXMAPPER_VERSION
      - name: Download libs
        run: |
          curl -O https://repo1.maven.org/maven2/com/googlecode/libphonenumber/carrier/${{ CARRIER_VERSION }}/carrier-${{ CARRIER_VERSION }}.jar
          curl -O https://repo1.maven.org/maven2/com/googlecode/libphonenumber/prefixmapper/${{ PREFIXMAPPER_VERSION }}/prefixmapper-${{ PREFIXMAPPER_VERSION }}.jar
      - uses: actions/upload-artifact@v4
        with:
          name: libphonenumber-artifacts
          if-no-files-found: error
          path: |
            /carrier-*.jar
            /prefixmapper-*.jar
            java/libphonenumber/target/libphonenumber-*-no-metadata.jar
            java/libphonenumber/src/com/google/i18n/phonenumbers/data/*
            
